package pr_se.gogame.model;

public enum GameCommand {

    INIT, WHITSTARTS, BLACKSTARTS, WHITEWON, BLACKWON, PLAYBACK, CONFIRMCHOICE, DRAW,
    BLACKPLAYS, WHITEPLAYS, BLACKREMOVED, WHITEREMOVED, BLACKHANDICAP, WHITEHANDICAP, // Added by Gerald, TODO: Could BLACKPLAYS be replaced with BLACKSTURN?

    //GamePlay Setting Commands
    CONFIGCONFIRMATION, CONFIGSHOWMOVENUMBERS, CONFIGSHOWCOORDINATES,
    //Debug Commands
    DEBUGINFO // TODO: Remove in final product
}
