package pr_se.gogame.model;

public enum GameCommand {

    INIT, WHITSTARTS, BLACKSTARTS,WHITWON, BLACKWON, PLAYBACK, CONFIRMCHOICE, START, DRAW,
    BLACKPLAYS, WHITEPLAYS, BLACKREMOVED, WHITEREMOVED, BLACKHANDICAP, WHITEHANDICAP, // Added by Gerald, TODO: Could BLACKPLAYS be replaced with BLACKSTURN?

    //GamePlay Setting Commands
    ENABLECONFIRMATION, DISABLECONFIRMATION,

    ENABLEMOVENUMBERS, //Debug Commands
    DISABLEMOVENUMBERS, ENABLECOORDINATES, DISABLECOORDINATES, DEBUGINFO // TODO: Remove in final product
}
